<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('scan_source', 'doctrine');

/**
 * Basescan_source
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property nvarchar $source_name
 * @property integer $source_type_id
 * @property nvarchar $url
 * @property boolean $disabled
 * @property Doctrine_Collection $scan_data
 * @property Doctrine_Collection $playlist_data
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method nvarchar            getSourceName()     Returns the current record's "source_name" value
 * @method integer             getSourceTypeId()   Returns the current record's "source_type_id" value
 * @method nvarchar            getUrl()            Returns the current record's "url" value
 * @method boolean             getDisabled()       Returns the current record's "disabled" value
 * @method Doctrine_Collection getScanData()       Returns the current record's "scan_data" collection
 * @method Doctrine_Collection getPlaylistData()   Returns the current record's "playlist_data" collection
 * @method scan_source         setId()             Sets the current record's "id" value
 * @method scan_source         setSourceName()     Sets the current record's "source_name" value
 * @method scan_source         setSourceTypeId()   Sets the current record's "source_type_id" value
 * @method scan_source         setUrl()            Sets the current record's "url" value
 * @method scan_source         setDisabled()       Sets the current record's "disabled" value
 * @method scan_source         setScanData()       Sets the current record's "scan_data" collection
 * @method scan_source         setPlaylistData()   Sets the current record's "playlist_data" collection
 * 
 * @package    RSSMonitor
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basescan_source extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scan_source');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('source_name', 'nvarchar', 100, array(
             'type' => 'nvarchar',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('source_type_id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('url', 'nvarchar', 1000, array(
             'type' => 'nvarchar',
             'notnull' => false,
             'length' => 1000,
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('scan_data', array(
             'local' => 'id',
             'foreign' => 'scan_source_id'));

        $this->hasMany('playlist_data', array(
             'local' => 'id',
             'foreign' => 'scan_source_id'));
    }
}