<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('source_type', 'doctrine');

/**
 * Basesource_type
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property nvarchar $type_name
 * @property varchar $processor_class
 * @property boolean $disabled
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method nvarchar    getTypeName()        Returns the current record's "type_name" value
 * @method varchar     getProcessorClass()  Returns the current record's "processor_class" value
 * @method boolean     getDisabled()        Returns the current record's "disabled" value
 * @method source_type setId()              Sets the current record's "id" value
 * @method source_type setTypeName()        Sets the current record's "type_name" value
 * @method source_type setProcessorClass()  Sets the current record's "processor_class" value
 * @method source_type setDisabled()        Sets the current record's "disabled" value
 * 
 * @package    RSSMonitor
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesource_type extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('source_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'size' => 4,
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('type_name', 'nvarchar', 100, array(
             'type' => 'nvarchar',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('processor_class', 'varchar', 60, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 60,
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}