<?php

/**
 * playlist_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class playlist_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object playlist_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('playlist_data');
    }
}