<?php

/**
 * scan_songTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class scan_songTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object scan_songTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('scan_song');
    }
}