<?php

/**
 * scan_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class scan_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object scan_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('scan_data');
    }
}