<?php

/**
 * scan_song
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RSSMonitor
 * @subpackage model
 * @author     Anvaya Technologies
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class scan_song extends Basescan_song
{

}