<?php

/**
 * scan_sourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class scan_sourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object scan_sourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('scan_source');
    }
}