<?php

/**
 * source_typeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class source_typeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object source_typeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('source_type');
    }
}