# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:     
      dsn: sqlsrv:Server=XPWINDOWS7\SQLEXPRESS;Database=dbRssCMS;MultipleActiveResultSets=false
      username: ASPUSER
      password: m2253327
      encoding: UTF-8      
      attributes:
        tblname_format: rss_%s    
  
  SngCMS:
    class: sfDoctrineDatabase
    param:     
      dsn: sqlsrv:Server=XPWINDOWS7\SQLEXPRESS;Database=dbSngCMS;MultipleActiveResultSets=false
      #dsn: sqlsrv:Server=WIN7\SQLEXPRESS;Database=dbSngCMS;MultipleActiveResultSets=false
      #dsn: odbc:SngCMS
      username: ASPUSER
      password: m2253327
      encoding: UTF-8      
      attributes:
        tblname_format: cms_%s    
        
